// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_riae.Models;

#nullable disable

namespace backriae.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20221207214104_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("back_riae.Models.boleta_clasificadores", b =>
                {
                    b.Property<int>("id_boleta_clasificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_boleta_clasificador"));

                    b.Property<int>("cod_clasificador")
                        .HasColumnType("int");

                    b.Property<int?>("codigo")
                        .HasColumnType("int");

                    b.Property<float>("importe_unitario_clasificador")
                        .HasColumnType("real");

                    b.Property<string>("nombre_clasificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_registro")
                        .HasColumnType("int");

                    b.HasKey("id_boleta_clasificador");

                    b.ToTable("boleta_Clasificadores");
                });

            modelBuilder.Entity("back_riae.Models.registro_frotatorios", b =>
                {
                    b.Property<int>("id_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_registro"));

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_subtipo")
                        .HasColumnType("int");

                    b.Property<int>("id_tipo_registro")
                        .HasColumnType("int");

                    b.Property<float>("igv")
                        .HasColumnType("real");

                    b.Property<float?>("importe_deposito")
                        .HasColumnType("real");

                    b.Property<float>("importe_total_boleta")
                        .HasColumnType("real");

                    b.Property<float?>("importe_total_tipo_fr")
                        .HasColumnType("real");

                    b.Property<float?>("importe_total_tipo_ip")
                        .HasColumnType("real");

                    b.Property<float?>("monto_cheque")
                        .HasColumnType("real");

                    b.Property<float>("monto_igv")
                        .HasColumnType("real");

                    b.Property<float?>("monto_nota_abono")
                        .HasColumnType("real");

                    b.Property<float?>("monto_voucher")
                        .HasColumnType("real");

                    b.Property<int>("n_boleta")
                        .HasColumnType("int");

                    b.Property<int?>("n_cheque")
                        .HasColumnType("int");

                    b.Property<int?>("n_nota_abono")
                        .HasColumnType("int");

                    b.Property<float>("n_recibo")
                        .HasColumnType("real");

                    b.Property<int?>("n_voucher")
                        .HasColumnType("int");

                    b.Property<string>("nombre_banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_factura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nota_informativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("texto_glosa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_registro");

                    b.HasIndex("n_boleta");

                    b.ToTable("registro_Frotatorios");
                });

            modelBuilder.Entity("back_riae.Models.registro_ipropios", b =>
                {
                    b.Property<int>("id_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_registro"));

                    b.Property<int>("id_subtipo")
                        .HasColumnType("int");

                    b.Property<int>("id_tipo_registro")
                        .HasColumnType("int");

                    b.Property<float>("importe_total_boleta")
                        .HasColumnType("real");

                    b.Property<float?>("monto_cheque")
                        .HasColumnType("real");

                    b.Property<int>("n_boleta")
                        .HasColumnType("int");

                    b.Property<int?>("n_cheque")
                        .HasColumnType("int");

                    b.Property<float>("n_recibo")
                        .HasColumnType("real");

                    b.Property<string>("texto_glosa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_registro");

                    b.HasIndex("n_boleta");

                    b.ToTable("registro_Ipropios");
                });

            modelBuilder.Entity("back_riae.Models.subtipo_ingresos_fr", b =>
                {
                    b.Property<int>("id_subtipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_subtipo"));

                    b.Property<int>("id_tipo_registro")
                        .HasColumnType("int");

                    b.Property<string>("nombre_subtipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subtipo_registro")
                        .HasColumnType("int");

                    b.HasKey("id_subtipo");

                    b.ToTable("subtipo_Ingresos_FR");
                });

            modelBuilder.Entity("back_riae.Models.subtipo_ingresos_ip", b =>
                {
                    b.Property<int>("id_subtipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_subtipo"));

                    b.Property<int>("id_tipo_registro")
                        .HasColumnType("int");

                    b.Property<string>("nombre_subtipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subtipo_registro")
                        .HasColumnType("int");

                    b.HasKey("id_subtipo");

                    b.ToTable("subtipo_Ingresos_IP");
                });

            modelBuilder.Entity("back_riae.Models.tipos_ingresos", b =>
                {
                    b.Property<int>("id_tipo_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipo_registro"));

                    b.Property<string>("nombre_registro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_registro")
                        .HasColumnType("int");

                    b.HasKey("id_tipo_registro");

                    b.ToTable("tipos_Registros");
                });

            modelBuilder.Entity("back_riae.Models.registro_frotatorios", b =>
                {
                    b.HasOne("back_riae.Models.boleta_clasificadores", "boleta_clasificadores")
                        .WithMany()
                        .HasForeignKey("n_boleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("boleta_clasificadores");
                });

            modelBuilder.Entity("back_riae.Models.registro_ipropios", b =>
                {
                    b.HasOne("back_riae.Models.boleta_clasificadores", "boleta_clasificadores")
                        .WithMany()
                        .HasForeignKey("n_boleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("boleta_clasificadores");
                });
#pragma warning restore 612, 618
        }
    }
}
